version: '3.8'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - ../db:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - digitalisim_net

  web:
    image: digitalisim
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql+pymysql://root:my-secret-pw@db/communes_db"
      NOMINATIM_URL: "http://nominatim:8080/search"
      MYSQL_ROOT_PASSWORD: my-secret-pw
    depends_on:
      - db
      - nominatim
    networks:
      - digitalisim_net
    entrypoint: ["./wait-for-it.sh", "db", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  nominatim:
    image: mediagis/nominatim:4.4
    environment:
      PBF_URL: "https://download.geofabrik.de/europe/monaco-latest.osm.pbf"
      REPLICATION_URL: "https://download.geofabrik.de/europe/monaco-updates/"
    ports:
      - "8080:8080"
    networks:
      - digitalisim_net

networks:
  digitalisim_net: