openapi: 3.0.0
info:
  title: Digitalisim API
  description: API for managing and retrieving information about communes.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000
    description: Local server

paths:
  /communes/{commune_name}:
    get:
      summary: Retrieve information about a commune by its name
      parameters:
        - name: commune_name
          in: path
          required: true
          description: The name of the commune
          schema:
            type: string
      responses:
        '200':
          description: A single commune's details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommuneResponse'
        '404':
          description: Commune not found

  /departments/{department_code}/communes:
    get:
      summary: Retrieve all communes in a department
      parameters:
        - name: department_code
          in: path
          required: true
          description: The code of the department
          schema:
            type: string
      responses:
        '200':
          description: A list of communes in the department
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CommuneResponse'
        '404':
          description: Department not found

  /geocoding/geocode/{city_name}:
    get:
      summary: Retrieve the GPS coordinates of a city
      parameters:
        - name: city_name
          in: path
          required: true
          description: The name of the city
          schema:
            type: string
      responses:
        '200':
          description: The coordinates of the city
          content:
            application/json:
              schema:
                type: object
                properties:
                  city:
                    type: string
                  latitude:
                    type: string
                  longitude:
                    type: string
        '404':
          description: Coordinates not found for the city

components:
  schemas:
    CommuneResponse:
      type: object
      properties:
        code_postal:
          type: string
        nom_commune_complet:
          type: string
        code_departement:
          type: integer
          nullable: true
        nom_departement:
          type: string
          nullable: true
